name: Feature Request Greeting

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Check if the issue is labeled as a Feature Request
      id: check_feature_label
      run: |
        LABELS=$(jq -r '.issue.labels[].name' "$GITHUB_EVENT_PATH")
        if echo "$LABELS" | grep -q 'New Feature'; then
          echo "This issue is labeled as a feature request. Sending greeting message."
          echo "skip=false" >> $GITHUB_ENV
        else
          echo "This issue is not labeled as a feature request. Skipping greeting message."
          echo "skip=true" >> $GITHUB_ENV
        fi

    - name: Send Greeting Message
      if: env.skip != 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const issueNumber = context.payload.issue.number;
          const message = `
          **💡 Thank you for your feature request!**  
          Your request has been successfully submitted and is now under consideration. We value your input in shaping the future of Awery.

          **📈 What to Expect Next**  
          - Our team will review your request and assess its feasibility.  
          - We may reach out for additional details or clarification.  
          - Updates on the request will be provided, and it may be scheduled for future development.

          **👥 Stay Connected**  
          - **[Discord](https://discord.com/invite/yspVzD4Kbm)**: Join our community to discuss ideas and stay updated.  
          - **[Telegram](https://t.me/mrboomdev_awery)**: Connect with us directly for real-time updates.

          We appreciate your suggestion and look forward to potentially implementing it!
          `;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: message
          });
