name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, looks like this is your first Issue in this repository! If you have any questions, please visit us: https://discord.com/invite/yspVzD4Kbm"
        pr-message: "Thank you for your efforts! Your Pull Request will be reviewed soon, but in the meantime you can sit with us: https://discord.com/invite/yspVzD4Kbm"
