name: Greetings

on:
  pull_request:
  pull_request_target:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Check if the PR creator is the repo owner
      id: check_owner
      run: |
        PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        REPO_OWNER=$(jq -r '.repository.owner.login' "$GITHUB_EVENT_PATH")
        if [ "$PR_AUTHOR" = "$REPO_OWNER" ]; then
          echo "The PR creator is the repository owner. Skipping greeting message."
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "The PR creator is not the repository owner. Sending greeting message."
          echo "skip=false" >> $GITHUB_ENV
        fi

    - name: Send Greeting Message
      if: env.skip != 'true'
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
          **🎉 Thank you for your contribution!**  
          Your Pull Request has been successfully submitted and is now awaiting review. We truly appreciate your efforts to improve Awery.

          **👥 Connect with the Community**  
          While you're here, why not join our communities to stay engaged?  
          - **[Discord](https://discord.com/invite/yspVzD4Kbm)**: Chat with fellow developers, ask questions, and get the latest updates.  
          - **[Telegram](https://t.me/mrboomdev_awery)**: Connect directly with us for real-time discussions and updates.

          **📋 What to Expect Next**  
          - Your Pull Request will be reviewed by our team as soon as possible.  
          - You'll receive notifications if further information or changes are needed.  
          - Once approved, your changes will be merged into the main project.

          We’re excited to collaborate with you. Stay tuned for updates!
